// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify connectivity.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool2({
  name: "app_info",
  title: "App info",
  description: "Return basic information about this admin platform (\u5C45\u7136\u8BBE\u8BA1\u5BB6 \u7BA1\u7406\u540E\u53F0).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "\u5C45\u7136\u8BBE\u8BA1\u5BB6 \u7BA1\u7406\u540E\u53F0",
            description: "3D \u5BB6\u88C5\u8BBE\u8BA1 SaaS \u7684 B \u7AEF\u7BA1\u7406\u540E\u53F0\uFF0C\u8986\u76D6\u4F01\u4E1A\u7BA1\u7406\u3001\u6743\u76CA\u3001\u4EBA\u5458\u3001\u5546\u54C1\u3001\u8425\u9500\u3001\u5BA2\u6237\u7B49\u6A21\u5757\u3002",
            modules: [
              "enterprise",
              "staff",
              "brand",
              "product",
              "model",
              "entitlement",
              "customer",
              "marketing",
              "permission",
              "agent",
              "prd"
            ]
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gongzuotai-mcp",
  title: "\u5DE5\u4F5C\u53F0 MCP",
  version: "0.1.0",
  instructions: "\u5C45\u7136\u8BBE\u8BA1\u5BB6\u7BA1\u7406\u540E\u53F0\u7684 MCP \u670D\u52A1\u3002\u4F7F\u7528 `echo` \u9A8C\u8BC1\u8FDE\u901A\u6027\uFF0C\u4F7F\u7528 `app_info` \u83B7\u53D6\u5E73\u53F0\u4FE1\u606F\u3002",
  tools: [echo_default, app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
